"""add phone column

Revision ID: 9371abc0ed5d
Revises: ec83a2acf059
Create Date: 2024-10-09 12:51:39.572913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9371abc0ed5d'
down_revision: Union[str, None] = 'ec83a2acf059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'phone')
    # ### end Alembic commands ###
