version: "3"

services:
  paric_bot:
    restart: always
    image: paric_bot:latest
    ports:
      - "8081:80"



  nginx_bot:
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled










