version: "3"

services:
  bot:
    build: ./docker/bot
    restart: always
    volumes:
      - .:.
#    image: paric_bot:latest

  api:
    build: ./docker/api
    restart: always
    volumes:
      - .:.


  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro










